// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2eWNadImrKOqM6smxilvn47b8MybRbg',
    appId: '1:858436204945:web:242505efa8c9732a3f4230',
    messagingSenderId: '858436204945',
    projectId: 'first-time-firebase-6dbed',
    authDomain: 'first-time-firebase-6dbed.firebaseapp.com',
    storageBucket: 'first-time-firebase-6dbed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvioA_yfsGfZqqtApheQ_3JXEHlX45I0',
    appId: '1:858436204945:android:ca56e0bfc6cac42c3f4230',
    messagingSenderId: '858436204945',
    projectId: 'first-time-firebase-6dbed',
    storageBucket: 'first-time-firebase-6dbed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeznYxNZf5_5NsQQIS9VAvMKA3jtKnus',
    appId: '1:858436204945:ios:55be9a818bef0c2a3f4230',
    messagingSenderId: '858436204945',
    projectId: 'first-time-firebase-6dbed',
    storageBucket: 'first-time-firebase-6dbed.appspot.com',
    iosBundleId: 'com.example.flutterStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOeznYxNZf5_5NsQQIS9VAvMKA3jtKnus',
    appId: '1:858436204945:ios:55be9a818bef0c2a3f4230',
    messagingSenderId: '858436204945',
    projectId: 'first-time-firebase-6dbed',
    storageBucket: 'first-time-firebase-6dbed.appspot.com',
    iosBundleId: 'com.example.flutterStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd2eWNadImrKOqM6smxilvn47b8MybRbg',
    appId: '1:858436204945:web:40f749031e234dec3f4230',
    messagingSenderId: '858436204945',
    projectId: 'first-time-firebase-6dbed',
    authDomain: 'first-time-firebase-6dbed.firebaseapp.com',
    storageBucket: 'first-time-firebase-6dbed.appspot.com',
  );
}
